theme = "period"

baseURL = "https://www.fractalog.com"
copyright = "© FractaLog All rights reserved"
paginate = 10
title = "FractaLog"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2


[params]
subTitle = "Model-Predict-Understand...A non-linear space for students of Chaos and Fractals."

[params.cdn.js]
highlightjs = "https://cdn.bootcdn.net/ajax/libs/highlight.js/10.3.2/highlight.min.js"
jquery = "https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"

[params.cdn.css]
highlightjs = "https://cdn.bootcdn.net/ajax/libs/highlight.js/10.3.2/styles/an-old-hope.min.css"

[params.comment]
repo = "{org}/{repo}"
show = false
theme = "github-light"


[params.widget.links]
show = true
title = "Friendly Links"

[[params.widget.links.items]]
title = "Hugo Themes"
url = "https://hugothemesfree.com/"



[params.widget.oldtestament]
show = true
title = "oldtestament"

[params.widget.tags]
show = true
title = "Tags"
